name:                reason-export
version:             0.1.1.0
github:              "abarbu/reason-export"
license:             MIT
author:              "Andrei Barbu"
maintainer:          "andrei@0xab.com"
copyright:           "2019 Andrei Barbu"

extra-source-files:
- README.md
- ChangeLog.md
- test/*.re

synopsis:            Generate Reason types from Haskell
category:            Web
description:         Please see the README on GitHub at <https://github.com/abarbu/reason-export#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- text
- time
- hashable
ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - Reason
  dependencies:
  - directory
  - formatting
  - mtl
  - wl-pprint-text

tests:
  reason-export-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reason-export
    - Diff
    - HUnit
    - QuickCheck
    - hspec
    - hspec-core
    - quickcheck-instances
